[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "test-foundry"
evm_version = "prague"
optimizer = true
optimizer_runs = 200
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
]

[profile.default.rpc_endpoints]
sepolia = "https://rpc.sepolia.org"
mainnet = "https://eth.publicrpc.com"
